import type { Speaker } from "./types";

// ─── Expertise tags for the bottom marquee ─────────────────────────────────────

export const EXPERTISE_TAGS: string[] = [
  "GIS Analysis",
  "Remote Sensing",
  "UAV Operations",
  "LiDAR Processing",
  "Spatial Databases",
  "Precision Agriculture",
  "Oil Field Intelligence",
  "Cadastral Systems",
  "Digital Twins",
  "AI-Powered Mapping",
  "SAR Interpretation",
  "Environmental Monitoring",
  "Coastal Mapping",
  "Python & QGIS",
  "ArcGIS Enterprise",
  "Drone Photogrammetry",
  "Land Administration",
];

// ─── Speaker roster data ────────────────────────────────────────────────────────

export const SPEAKERS: Speaker[] = [
  {
    id: 1,
    initials: "AK",
    name: "Dr. Adaeze Kalu",
    title: "Principal GIS Scientist",
    org: "Federal Ministry of Environment, Nigeria",
    role: "host",
    category: "GIS & Spatial Mapping",
    webinars: 6,
    bio: "Dr. Kalu is a pioneer in applied geospatial science across Sub-Saharan Africa, with over 18 years of experience in land use mapping, environmental monitoring, and spatial data infrastructure development for government agencies. She holds a PhD in Geoinformatics from ITC Netherlands.",
    linkedin: "#",
    expertise: ["GIS Analysis", "Environmental Monitoring", "Spatial Policy"],
    accentColor: "rgba(0,80,160,0.3)",
  },
  {
    id: 2,
    initials: "RO",
    name: "Engr. Raymond Okonkwo",
    title: "UAV Systems Lead",
    org: "Shell Nigeria Exploration",
    role: "host",
    category: "Drone Surveys",
    webinars: 4,
    bio: "Raymond leads UAV survey operations for offshore and onshore pipeline surveillance across the Niger Delta. His work on autonomous drone corridors has been cited in IEEE Geoscience journals. He is a certified remote pilot with over 2,000 flight hours.",
    linkedin: "#",
    expertise: ["UAV Operations", "Pipeline Surveillance", "Oil Field Intelligence"],
    accentColor: "rgba(0,180,120,0.25)",
  },
  {
    id: 3,
    initials: "FM",
    name: "Dr. Fatima Musa",
    title: "Senior Remote Sensing Analyst",
    org: "NASRDA — Space Agency Nigeria",
    role: "guest",
    category: "Remote Sensing",
    webinars: 3,
    bio: "Dr. Musa specialises in SAR and multispectral satellite data processing for national security and environmental risk assessment. She has contributed to flood early-warning systems serving over 3 million Nigerians across the Benue River basin.",
    linkedin: "#",
    expertise: ["SAR Interpretation", "Flood Mapping", "Satellite Analytics"],
    accentColor: "rgba(0,120,200,0.25)",
  },
  {
    id: 4,
    initials: "CE",
    name: "Chief Emmanuel Effiong",
    title: "Executive Director, Geospatial Services",
    org: "NNPC Upstream",
    role: "host",
    category: "Oil & Gas",
    webinars: 5,
    bio: "Chief Effiong oversees all geospatial operations for NNPC's upstream division, managing a portfolio of 14 active fields across the Niger Delta and deep-water blocks. He championed the first digital twin initiative for Nigerian oilfield development planning.",
    linkedin: "#",
    expertise: ["Digital Twins", "Oil Field Intelligence", "Regulatory Compliance"],
    accentColor: "rgba(200,80,0,0.22)",
  },
  {
    id: 5,
    initials: "LB",
    name: "Lara Bello, MSc",
    title: "Precision Agriculture Consultant",
    org: "AfricaRice / CGIAR",
    role: "guest",
    category: "Precision Agriculture",
    webinars: 3,
    bio: "Lara works at the intersection of satellite imagery and smallholder farming, designing crop monitoring dashboards for over 40,000 rice farmers in Ebonyi and Kebbi States. Her soil-health spectral indices have been adopted by two West African governments.",
    linkedin: "#",
    expertise: ["Precision Agriculture", "Crop Yield Analytics", "NDVI Analysis"],
    accentColor: "rgba(80,160,0,0.22)",
  },
  {
    id: 6,
    initials: "HI",
    name: "Barrister Haruna Ibrahim",
    title: "Director of Land Administration",
    org: "Rivers State Government",
    role: "host",
    category: "Land Administration",
    webinars: 2,
    bio: "Barrister Ibrahim has spent two decades reforming land tenure law in Rivers State, spearheading Nigeria's first fully paperless cadastral registration system. His work has reduced land dispute litigation by 68% in Port Harcourt Metropolitan Area.",
    linkedin: "#",
    expertise: ["Cadastral Systems", "Land Administration", "Property Law"],
    accentColor: "rgba(160,100,0,0.22)",
  },
  {
    id: 7,
    initials: "TW",
    name: "Tunde Williams",
    title: "LiDAR & Photogrammetry Expert",
    org: "Fugro West Africa",
    role: "guest",
    category: "Drone Surveys",
    webinars: 4,
    bio: "Tunde leads LiDAR acquisition and point-cloud processing projects across West Africa, delivering topographic datasets for major infrastructure projects including the Lagos-Ibadan expressway expansion and Dangote Refinery site surveys.",
    linkedin: "#",
    expertise: ["LiDAR Processing", "Drone Photogrammetry", "Point Cloud Analysis"],
    accentColor: "rgba(100,0,180,0.2)",
  },
  {
    id: 8,
    initials: "NK",
    name: "Dr. Ngozi Kanu",
    title: "Head of Spatial Analytics",
    org: "University of Port Harcourt",
    role: "guest",
    category: "GIS & Spatial Mapping",
    webinars: 3,
    bio: "Dr. Kanu leads the department of Geospatial Engineering at UNIPORT, combining academic rigour with applied research. Her lab has produced 24 PhD graduates now leading geospatial practices across 12 African nations.",
    linkedin: "#",
    expertise: ["Spatial Databases", "Python & QGIS", "ArcGIS Enterprise"],
    accentColor: "rgba(0,180,180,0.2)",
  },
];
